# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d918c5d6db100a31f98a3996c18580041a8d46cd57fc375b689eeb5648aa65d5e07235726725a819ad51de361fd78ad0fecd44d712de60c1366e2d0f8c3a5c2a

test:
  secret_key_base: 7d64407a393d78334a31dfd81d76fc73cfe5dbe1c14bc7f9d0119befb266827088dad45b9232fcdbb2faaf06dea1ea1068278863cd1d3cd5616ed4d143902b9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
